---
# tasks file for ca_certificates

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Debugging
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_release }} / {{ ansible_distribution }} / {{ ansible_os_family }}"

- name: Installing Unbound Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ unbound_packages }}"

- name: Include OS specific tasks if defined
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      skip: true

- name: Ensure unbound is running
  ansible.builtin.service:
    name: "{{ unbound_service_name }}"
    state: started
    enabled: true

- name: Check if port 53 is open
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 53
